/* A program to guess the number generated by the computer. A successfull guess
will mention the same and an insuccessfull one will tell you to increase and
decrease the number accordingly.

Once you successfully guess the number it will
show the number of attempts it took for you to guess the number.

You can play the game with your friends and the one who can guess it in less number of attempts
will be the winner :)
*/
#include <iostream>
#include <stdlib.h>
#include <time.h>
using namespace std;
int main()
{
    int number, guess, i = 1;
    srand(time(0));
    number = rand() % 100 + 1;
    // cout << number << endl;
    do
    {
        cout << " Please guess the number - ";
        cin >> guess;
        if (number == guess)
            cout << "Correct guess in " << i << " attempts." << endl;
        else if (guess > number)
            cout << "Your guess is bigger. ";
        else
            cout << "Your guess is smaller. ";
        i++;
    } while (guess != number);

    return 0;
}
